---
- name: provision vm
  hosts: localhost
  become: false

  tasks:
    - name: Create VM with defaults
      azure_rm_virtualmachine:
        resource_group: test
        name: testvm10
        admin_username: sdunne 
        admin_password: r3dh4t1! 
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '7.1'
          version: latest

