---
- hosts: localhost
  connection: local
  become: false
  tasks:
    - name: create resource group
      azure_rm_resourcegroup:
        name: ansible-rg
        location: eastus
      register: rg
    - debug:
        var: rg

