---

- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/main.yml
#  vars:
          #    instance_type: "ami-0af6f794ec2d5ff13" #rhel7 imported
#    instance_type: "ami-011b3ccf1bd6db744" #rhel76 from aws
#    key_name: "sd2rh"
#    public_subnet_id: subnet-0e412cca60ccd15b7 #sdunne-sub1
#    security_group: sdunne-sg-default

  tasks:

    - name: provision a set of instances
      ec2:
        key_name: "{{ key_name }}"
#        group: test
        vpc_subnet_id: "{{ public_subnet_id }}"
        group: "{{ security_group }}"
        region: us-east-1
        instance_type: t2.small
        image: "{{ instance_type }}"
        assign_public_ip: yes
        wait: true
#        exact_count: 1
#        count_tag:
#          Name: sdunne-demo
        instance_tags:
          Name: sdunne-demo1
      register: ec2
