---

- hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - vars/main.yml

  tasks:

    - name: Gather EC2 facts
      ec2_instance_facts:
        region: "{{ aws_region }}"
        filters:
          "tag:Name": sdunne*
      register: ec2_facts

    - name: Terminate EC2 VMs
      ec2:
        state: "absent"
        region: "{{ aws_region }}"
        instance_ids: "{{ item.instance_id }}"
        wait: yes
      with_items: "{{ ec2_facts.instances }}"
      when: item.state != 'terminated'
